Add GitHub Actions for automatic release
omnitool-ai/omnitool pull request #1
Opened 2023-12-24 10:01 UTC by appleparan

Hello, when I first discovered this project, it seemed like a product still under development as there were no releases yet. So, I wanted to make a small contribution: I've added GitHub Actions for automated releases. 

# What I added
* [ghalactic/github-release-from-tag](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file)
# How to use it
  1. Add Git alias for [Markdown support](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file#markdown-support)
  2. When adding tags use following commands. Change `v0.6.3` to whatever, but with 'v' prefix (ref. [this section](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file#release-stability))
  ```
  git tag-md v0.6.3
  ```
  3. Write subject and body as you want using Markdown. For example:
  ```
  OmniTool 0.6.3 Update

  # Development Updates: Enhanced Automation

  *  Added GitHub Actions for Improved Workflow
    *  Automated Deployment: Enables automatic release generation
  ```
  4. [Final result](https://github.com/appleparan/omnitool/releases/tag/v0.6.3)
  5. I have set it up to automatically add reactions, but if you don't want them, you can remove `reactions: +1, laugh, hooray, heart, rocket, eyes` from `.github/workflows/publish-release.yml`

2023-12-28 01:08 UTC, weiyi commented
Thanks for submitting this PR! We'll roll this into our publish pipeline in a future version.

2024-01-02 01:32 UTC, weiyi commented
> Hello, when I first discovered this project, it seemed like a product still under development as there were no releases yet. So, I wanted to make a small contribution: I've added GitHub Actions for automated releases.
> 
> # What I added
> * [ghalactic/github-release-from-tag](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file)
> 
> # How to use it
> 1. Add Git alias for [Markdown support](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file#markdown-support)
> 2. When adding tags use following commands. Change `v0.6.3` to whatever, but with 'v' prefix (ref. [this section](https://github.com/ghalactic/github-release-from-tag?tab=readme-ov-file#release-stability))
> 
> ```
> git tag-md v0.6.3
> ```
> 
> 3. Write subject and body as you want using Markdown. For example:
> 
> ```
> OmniTool 0.6.3 Update
> 
> # Development Updates: Enhanced Automation
> 
> *  Added GitHub Actions for Improved Workflow
>   *  Automated Deployment: Enables automatic release generation
> ```
> 
> 4. [Final result](https://github.com/appleparan/omnitool/releases/tag/v0.6.3)
> 5. I have set it up to automatically add reactions, but if you don't want them, you can remove `reactions: +1, laugh, hooray, heart, rocket, eyes` from `.github/workflows/publish-release.yml`
> 
> # How to test locally
> * You can test with [act](https://github.com/nektos/act), but this only tests if the workflow runs successful and does not test detailed aspects like formatting.

Hey @appleparan! We've tested this with our publish pipeline and it looks good to go. Let's leave the reactions commented out for now though :) If you can make that change, we'll merge this PR in.

2024-01-02 01:35 UTC, weiyi commented on .github/workflows/publish-release.yml
> +          reactions: +1,laugh,hooray,heart,rocket,eyes
lets use just 1, my vote is for rocket!

2024-01-02 01:35 UTC, weiyi requested changes
check notes below

2024-01-02 08:11 UTC, appleparan commented
I pushed a commit and rebased as you requested.  I hope it would be helpful.

Anyway, It seems like there's a lot of work to do, but it looks like a interesting project. I'll try to contribute more if I come up with new ideas.

2024-01-02 11:30 UTC, weiyi approved these changes

2024-01-02 11:43 UTC, merged